NAME = pruebapruebapruebaprueba

CFLAGS = -Wall -Werror -Wextra

SRCS = main.cpp Prueba.cpp Prueba.cpp Prueba.cpp Prueba.cpp

OBJS = $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	clang++ $(CFLAGS) $(OBJS) -o $(NAME)

clean:
	rm -f $(OBJS)

fclean:	clean
	rm -f $(NAME)

re:	fclean all

.PHONY: all clean fclean re
